apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8stest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : k8test-label
    spec:
      containers:
        - name: k8stest-container
          image: ernom/k8stest:v1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 80